-- T1D Saathi - Tables & Triggers
CREATE TABLE IF NOT EXISTS profiles (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES auth.users(id) UNIQUE NOT NULL, full_name TEXT, avatar_url TEXT, role TEXT DEFAULT 'parent' CHECK (role IN ('parent', 'clinician')), created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS patients (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES auth.users(id) NOT NULL, name TEXT NOT NULL, date_of_birth TEXT, sex TEXT CHECK (sex IN ('male', 'female', 'other')), photo_uri TEXT, comorbid_conditions TEXT[], medications TEXT, insulin_type TEXT NOT NULL, insulin_dose NUMERIC DEFAULT 0, insulin_frequency TEXT, insulin_delivery TEXT CHECK (insulin_delivery IN ('pen', 'syringe', 'pump')), diagnosis_date TEXT, dka_history JSONB, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS insulin_regimens (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), patient_id UUID REFERENCES patients(id) ON DELETE CASCADE NOT NULL, insulin_type TEXT NOT NULL, dose NUMERIC DEFAULT 0, frequency TEXT, delivery_method TEXT CHECK (delivery_method IN ('pen', 'syringe', 'pump')), isf NUMERIC, carb_ratio NUMERIC, tdd NUMERIC, correction_target NUMERIC DEFAULT 120, effective_date TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sick_day_episodes (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), patient_id UUID REFERENCES patients(id) ON DELETE CASCADE NOT NULL, user_id UUID REFERENCES auth.users(id) NOT NULL, start_date TIMESTAMPTZ DEFAULT NOW(), end_date TIMESTAMPTZ, symptoms JSONB, outcome TEXT, escalated BOOLEAN DEFAULT false);
CREATE TABLE IF NOT EXISTS glucose_logs (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), patient_id UUID REFERENCES patients(id) ON DELETE CASCADE NOT NULL, user_id UUID REFERENCES auth.users(id) NOT NULL, value NUMERIC NOT NULL, unit TEXT DEFAULT 'mgdl' CHECK (unit IN ('mgdl', 'mmol')), context TEXT DEFAULT 'routine' CHECK (context IN ('routine', 'sick_day')), timestamp TIMESTAMPTZ DEFAULT NOW(), carbs NUMERIC, insulin_given NUMERIC, notes TEXT);
CREATE TABLE IF NOT EXISTS ketone_logs (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), patient_id UUID REFERENCES patients(id) ON DELETE CASCADE NOT NULL, user_id UUID REFERENCES auth.users(id) NOT NULL, value NUMERIC, method TEXT DEFAULT 'blood' CHECK (method IN ('blood', 'urine', 'unknown')), timestamp TIMESTAMPTZ DEFAULT NOW(), episode_id UUID REFERENCES sick_day_episodes(id));
CREATE TABLE IF NOT EXISTS hospitals (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT NOT NULL, address TEXT, phone TEXT, region TEXT);
CREATE TABLE IF NOT EXISTS care_team (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), patient_id UUID REFERENCES patients(id) ON DELETE CASCADE NOT NULL, clinician_id UUID REFERENCES auth.users(id) NOT NULL, hospital_id UUID REFERENCES hospitals(id), role TEXT DEFAULT 'primary' CHECK (role IN ('primary', 'secondary')));
CREATE TABLE IF NOT EXISTS messages (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), thread_id UUID, sender_id UUID REFERENCES auth.users(id) NOT NULL, recipient_id UUID REFERENCES auth.users(id), body TEXT NOT NULL, related_log_id UUID, is_structured_advice BOOLEAN DEFAULT false, timestamp TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS education_content (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), topic TEXT NOT NULL, language TEXT DEFAULT 'en' CHECK (language IN ('en', 'ne')), media_url TEXT, thumbnail_url TEXT, "order" INTEGER DEFAULT 0, target_audience TEXT DEFAULT 'both' CHECK (target_audience IN ('patient', 'family', 'both')), description TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS assessment_responses (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), patient_id UUID REFERENCES patients(id) ON DELETE CASCADE NOT NULL, user_id UUID REFERENCES auth.users(id) NOT NULL, questionnaire_id TEXT NOT NULL, phase TEXT NOT NULL CHECK (phase IN ('pre', 'post')), answers JSONB, timestamp TIMESTAMPTZ DEFAULT NOW());
CREATE OR REPLACE FUNCTION handle_new_user() RETURNS TRIGGER AS $$ BEGIN INSERT INTO public.profiles (user_id, full_name, avatar_url, role) VALUES (NEW.id, NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'avatar_url', COALESCE(NEW.raw_user_meta_data->>'role', 'parent')); RETURN NEW; END; $$ LANGUAGE plpgsql SECURITY DEFINER;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
